config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root 'welcome#index'

  resources :preferences, :only => [:update]
  resources :surveys do
    resources :comments, :except => [:index, :show]
  end

  post '/tab_results' => 'surveys#tab_results'
  get '/tab_results' => 'surveys#results'
  get '/results' => 'surveys#results'


  get '/account/:id' => 'welcome#account', as: 'account'
  get '/about' => 'welcome#about', as: 'about'
  get '/admin' => 'admin#index'
  post '/comments/:id/vote/:direction' => 'comments#vote', as: 'vote'
  post '/feedback' => 'feedbacks#create', as: 'feedbacks'
  get '/survery/answers/chart' => 'surveys#answers_chart', as: 'survey_answers_charts'

  resources :users, :only => [:edit, :update]
end

app/controllers/welcome_controller.rb
# Handles the landing page
class WelcomeController < ApplicationController
  before_action :authenticate_user!, only: [:account]

  def index
  end

  def account
    @user = User.find(params[:id])
    @surveys = @user.surveys.paginate(:page => params[:page], :per_page => 10)
  end

  def about
    @feedback = Feedback.new
  end
end

app/views/welcome/_surveys.html.erb
 <table id="surveys" class="table table-striped">
  <thead>
    <tr>
      <th>Survey</th>
      <th>Results</th>
      <th>Edit</th>
      <th>Delete</th>
    </tr>
  </thead>
  <tbody>
    <% @surveys.each do |survey| %>
    <tr>
      <td><%= link_to survey.title, results_path(id: survey.id) %></td>
      <td>
        <% answer_array = [] %>
        <% survey.answers.each do |answer| %>
        <% answer_array.push(["#{answer.body}",answer.votes]) %>
        <% end %>
        <%= pie_chart(answer_array, legend: {position: 'none'}, width: "50px", height: "50px") %>
      </td>
      <td><i class="fa fa-pencil-square-o" aria-hidden="true"></i><%= link_to "edit", edit_survey_path(survey.id) %>
      </td>
      <td class="survey-user"><i class="fa fa-trash" aria-hidden="false"></i><%=link_to "delete",survey_path(survey.id), :method => :delete, data: { confirm: t('Are your sure you want to delete this survey?'), ok: t("buttons.yes_i'm_sure"), cancel: t("buttons.no_way_dude!") } %> </td>
    </tr>
    <% end %>
  </tbody>
</table>
<nav aria-label="Page navigation">
  <% if @surveys.any? %>
  <%= will_paginate @surveys, renderer: BootstrapPagination::Rails  %>
  <% else %>
  <p class="empty">No surveys yet.</p>
  <% end %>
</nav>

app/views/welcome/about.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <div class="page-header">
      <h1>SurveyMaker</h1>
    </div>
    <div class="media">
      <div class="media-body">
        <h4 class="media-heading">Thank you for visiting:</h4>
        <p>The code for this app can be found on <a href="https://github.com/DeweyBanks/Survey2">Github</a>. </p>
        <p>I would love your feedback. Please take the time to review my code, paying special attention to the specs. My goal with SurveyMaker was to not only build out database relationships but to build a thorough testing suite. </p>
        <p>So let me know what I missed, what I could/should have done differently. You will instantly become my bestfrend!</p>
        <p>Best,</p>
        <p>Michael Hall</p>
      </div>
    </div>
  </div>
</div>

<div class="row feedback-wrapper">
  <div class="col-md-6 col-md-offset-2">
    <div class="feedback">
      <div class="feedback-form">
      <div class="feedback-heading">
        <h4 class="media-heading">Send me some feedback:</h4>
      </div>
          <%= form_for @feedback do |f| %>
            <div class="form-group feedback">
              <%= f.text_area :body, :placeholder => "&#xf27a; your thoughts . . .".html_safe, style: 'font-family: FontAwesome, Arial', required: true, autofocus: true %>
            </div>
            <div class="form-group feedback">
              <%= f.email_field :email, :placeholder => "&#xf199; email".html_safe, style: 'font-family: FontAwesome, Arial', required: true, autofocus: true %>

            </div>
            <%= f.submit "Send", :class => "pure-button pure-button-primary" %>
          <% end %>
        </div>
    </div>
  </div>
</div>

app/views/welcome/account.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <div class="page-header">
      <h1>My Account</h1>
      <div class="btn-group" role="group">
        <button type="button" class="btn btn-info" data-toggle="modal" data-target="#surveysModal">
          My Surveys
        </button>
        <button type="button" class="btn btn-info" data-toggle="modal" data-target="#settingsModal">
          Settings
        </button>
      </div>
      <!--   Modal -->
      <div class="modal fade" id="surveysModal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <h4 class="modal-title"><%= @user.username %>'s Surveys</h4>
            </div>
            <div class="modal-body">
              <%= render :partial => 'surveys' %>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
          </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
      </div><!-- /.modal -->
    </div>
    <div class="media">
      <div class="media-left">
        <%= image_tag gravatar_url("#{current_user.email}", 64), alt: "#{current_user.username}" %>
      </div>
      <div class="media-body">
        <h4 class="media-heading"><%= @user.username %></h4>
        <%= @user.email %>
        <div class="media-body">
          <h4 class="media-heading"></h4>
          <%= button_to "Cancel my account", registration_path(resource_name), :type =>"button", :class => "btn btn-danger",  data: { confirm: t('Are you sure? This will Delete all of your surveys and can not be undone!'), ok: t("buttons.yes_i'm_sure."), cancel: t("buttons.no!_i_didn't_mean_it") }, method: :delete %>
          <!-- Modal -->
          <div class="modal fade" id="settingsModal" tabindex="-1" role="dialog" aria-labelledby="settingsModalLabel">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                  <h4 class="modal-title" id="settingsModalLabel">My Settings</h4>
                </div>
                <div class="modal-body">
                  <h2>Edit <%= resource_name.to_s.humanize %></h2>
                  <%= form_for(resource, as: resource_name, url: registration_path(resource_name), html: { method: :put }) do |f| %>
                  <div class="form-group">
                    <%= f.label :username %><br />
                    <%= f.text_field :username, autofocus: true %>
                  </div>
                  <div class="form-group">
                    <%= f.label :email %><br />
                    <%= f.email_field :email, autofocus: true, :required => true %>
                  </div>
                  <div class="form-group">
                    <%= f.label :password %> <i>(leave blank if you don't want to change it)</i><br />
                    <%= f.password_field :password, autocomplete: "off" %>
                    <% if @minimum_password_length %>
                    <br />
                    <em><%= @minimum_password_length %> characters minimum</em>
                    <% end %>
                  </div>
                  <div class="form-group">
                    <%= f.label :password_confirmation %><br />
                    <%= f.password_field :password_confirmation, autocomplete: "off" %>
                  </div>

                  <div class="form-group">
                    <%= f.label :current_password %> <i>(we need your current password to confirm your changes)</i><br />
                    <%= f.password_field :current_password, autocomplete: "off", :required => true %>
                  </div>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                  <%= f.submit "Update", :class => "btn btn-primary" %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="media-body">
        <h5 class="media-heading">Number of Surveys: <span class="badge"><%= @surveys.count %></span></h5>
      </div>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<div id="main-container" class="container-fluid">
<div class="row-fluid">
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="jumbotron">
    <h1 class="display-3">Welcome To SurveyMaker</h1>
      <% if user_signed_in? %>
        <% if !current_user.lat? && !current_user.lng? %>
          <p id="identifier" data-user="<%= current_user.id %>"></p>
        <% end %>
        <p class="lead">Hello <%= current_user.username %>, from here you can:</p>
        <p><%= link_to "Create a survey", new_survey_path, :class => "btn btn-lg btn-success" %>
      <% else %>
        <p>Sign in and create a survey or click below to see the surveys already created.</p>
        <p><%= link_to '<i class="fa fa-facebook" aria-hidden="true"></i> Sign up with Facebook'.html_safe,user_facebook_omniauth_authorize_path, :class => "btn btn-default  dropdown-toggle" %>
      <%= link_to '<i class="fa fa-envelope" aria-hidden="true"></i> Sign up with Email'.html_safe,new_user_registration_path, :class => "btn btn-default dropdown-toggle" %></p></p>
      <% end %>
      <%= link_to "See the surveys", surveys_path, :class => "btn btn-lg btn-success" %></p>
    </div>
  </div>
</div>