config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root 'welcome#index'

  resources :preferences, :only => [:update]
  resources :surveys do
    resources :comments, :except => [:index, :show]
  end

  post '/tab_results' => 'surveys#tab_results'
  get '/tab_results' => 'surveys#results'
  get '/results' => 'surveys#results'


  get '/account/:id' => 'welcome#account', as: 'account'
  get '/about' => 'welcome#about', as: 'about'
  get '/admin' => 'admin#index'
  post '/comments/:id/vote/:direction' => 'comments#vote', as: 'vote'
  post '/feedback' => 'feedbacks#create', as: 'feedbacks'
  get '/survery/answers/chart' => 'surveys#answers_chart', as: 'survey_answers_charts'

  resources :users, :only => [:edit, :update]
end

app/models/survey.rb
class Survey < ActiveRecord::Base
  belongs_to :user
  has_many :comments, dependent: :destroy
  accepts_nested_attributes_for :comments, :allow_destroy => true
  has_many :answers, dependent: :destroy
  accepts_nested_attributes_for :answers, :allow_destroy => true
  validates :user, :presence => true
  validates :answers, :presence => true
end

app/controllers/surveys_controller.rb
# Handles the Surveys
class SurveysController < ApplicationController
  before_action :get_survey, only: [:update, :edit, :show, :tab_results, :results, :destroy]
  before_action :authenticate_user!, only: [:edit, :create, :destroy]

  def index
    # if user is logged in get survey's from area
    #  'https://maps.googleapis.com/maps/api/geocode/json?latlng=' + position.coords.latitude + '%2C' + position.coords.longitude + '&language=en';
    @surveys = Survey.includes(:comments, :answers).paginate(:page => params[:page], :per_page => 10)
  end

  def create
    @survey = Survey.new(survey_params)
    @survey.answers.each do |x|
      if x.body.blank?
        x.destroy!
      end
    end
    unless @survey.title.end_with?('?')
      @survey.title += '?'
    end
    respond_to do |format|
      if @survey.save
        format.html { redirect_to :action => 'results', :id => @survey.id, notice: 'Survey was successfully created.' }
        format.json { render :results, status: :created, location: @survey }
      else
        format.html { render :new }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  def new
    @survey = Survey.new
  end

  def update
    # TODO
    # if an answer has been changed, remove it's votes
    @survey.update(survey_params)
    render :results
  end

  def destroy
    @survey.destroy
    flash[:notice] = 'Your survey has been removed'
    redirect_to account_path(current_user)
  end

  def results
    @total = @survey.answers.map {|answer| answer.votes}.sum
  end

  def tab_results
    @answer = Answer.find(params[:answer_id])
    @answer.votes += 1
    @answer.save!
    redirect_to :action => 'results', :id => @survey.id
  end

  def answers_chart
    @survey = Survey.find(params[:id])
    answer_array = []
    @survey.answers.each do |answer|
      answer_array.push(["#{answer.body}",answer.votes])
    end
    respond_to do |format|
      format.json { render json: answer_array }
    end
  end

  private

  def get_survey
    if params.has_key?(:id)
      @survey = Survey.find(params[:id])
    elsif params.has_key?(:survey_id)
      @survey = Survey.find(params[:survey_id])
    else
      redirect_to root_path
    end
  end

  def survey_params
    params.require(:survey).permit(
      :title,
      :user_id,
      answers_attributes: [:id, :body, :_destroy],
      comments_attributes: [:id, :body, :user_id, :_destroy]
      )
  end
end

app/views/surveys/_comments.html.erb
<% @survey.comments.order("up_vote desc").each do |comment| %>
<div class="row-fluid">
  <div class="col-sm-2">
    <div class="thumbnail">
      <%= image_tag gravatar_url("#{comment.user.email}", 64), alt: "#{comment.user.username}" %>
    </div>
  </div>
  <div class="col-sm-9">
    <div class="panel panel-default">
      <div class="panel-heading">
        <strong><%= comment.user.username %></strong> <span class="text-muted"><%= comment.created_at.strftime("%B, %d, %Y") %> </span>&nbsp
        <% if current_user && votable?(comment) %>
        <% span_uptag = '<span class="badge">' + comment.up_vote.to_s + '</span>' %>
        <%= link_to span_uptag.html_safe, vote_path(comment, 'up'),
        :method => "Post", :class => "fa fa-thumbs-up",
        :remote => true %>

        <% span_tag = '<span class="badge">' + comment.down_vote.to_s + '</span>' %>
        <%= link_to span_tag.html_safe, vote_path(comment, 'down'),
        :method => "Post", :class => "fa fa-thumbs-down",
        :remote => true %>
        <% else %>
        <i class="fa fa-thumbs-up" aria-hidden="true">
          <span class="badge"><%= comment.up_vote %></span>
        </i>
        <i class="fa fa-thumbs-down" aria-hidden="true">
          <span class="badge"><%= comment.down_vote %></span>
        </i>
        <% end %>

        <% if comment.user == current_user %>
        <%= link_to "", "#", :"data-comment-open" => "comment-edit", :class => "fa fa-wrench pull-right" %>

        <div class="comment" data-comment="comment-edit">
          <div class="comment-inner">
            <%= form_for ([@survey, comment]) do |f| %>
            <div class="form-group form-group-lg">
              <%= f.text_area :body, :autofocus => true %>
            </div>
            <a href="#" data-comment-close="comment-edit" type="button" class="btn btn-default ">
              Cancel
            </a>
            <%= link_to "Delete", survey_comment_path(@survey, comment), :method => :delete, :class => "btn btn-danger",  data: { confirm: t('Are you sure?'), ok: t("buttons.yes"), cancel: t("buttons.cancel") } %>
            <%= f.submit 'Save Changes', :class => "btn btn-success" %>
            <% end %>
            <a class="comment-close" data-comment-close="comment-edit" href="#">x</a>
          </div>
        </div>
        <% end %>
      </div>
      <div class="panel-body">
        <%= comment.body %>
      </div><!-- /panel-body -->
    </div><!-- /panel panel-default -->
  </div><!-- /col-sm-5 -->
</div>
<% end %>

app/views/surveys/_comments_form.html.erb
<div class="well well-lg">
  <%= form_for ([@survey, @survey.comments.build]) do |f| %>
  <% if @survey.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@survey.errors.count, "error") %> prohibited this survey from being saved:</h2>
    <ul>
      <% @survey.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

 <div class="form-group form-group-lg">
    <%= f.text_area :body, :autofocus => true, :placeholder=>"what's on your mind?" %>
  </div>

<div class="btn-toolbar" role="toolbar">
  <div class="btn-group" role="group">
    <a href="#commentForm" type="button" class="btn btn-default" data-toggle="collapse">
      Cancel
    </a>
    <%= f.submit 'Submit', :class => "btn btn-success" %>
    <% end %>
  </div>
</div>
</div>

app/views/surveys/_form.html.erb
<div class="row-fluid">
  <div class="col-md-8 col-md-offset-2">
    <div class="page-header">
      <h1>Create your survey</h1>
    </div>
    <%= nested_form_for @survey do |f| %>
    <% if @survey.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@survey.errors.count, "error") %> prohibited this survey from being saved:</h2>
      <ul>
        <% @survey.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <div class="form-group">
    <%= f.label :enter_a_question %><br>
      <%= f.text_field :title, :placeholder=>"question" %>
    </div>
    <label>Then add an answer for your question. Add as many answers as you like.</label>
    <div class="form-group">
      <%= f.fields_for :answers do |answer_form| %>
      <%= answer_form.text_field :body, :class=> "answers", :placeholder => "answer" %>
      <%= answer_form.link_to_remove "Remove this answer" %>
      <% end %>
      <p><%= f.link_to_add "+ Add an answer", :answers, :class => "btn btn-primary btn-xs" %></p>
    </div>
    <label>When you are finished create your survey.</label>
    <br>
    <%= f.submit 'Save', :class => "btn btn-success" %>
    <% end %>
  </div>
</div>

app/views/surveys/edit.html.erb
<section>
<%= render 'form' %>
<br>
<div class="row-fluid">
  <div class="col-md-8 col-md-offset-2">
    <%= link_to 'Show', results_path(id: @survey.id) %> |
    <%= link_to 'Back', account_path(current_user) %>
  </div>
</div>
</section>

app/views/surveys/index.html.erb
<div class="row-fluid">
  <div class="col-md-8 col-md-offset-2">
    <div class="page-header">
      <h1>The SurveyMaker Surveys</h1>
    </div>
    <table id="surveys" class="table table-striped">
      <thead>
        <tr>
          <th>Survey</th>
          <th>Results</th>
          <th>Created by:</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @surveys.each do |survey| %>
        <tr>
          <td><%= link_to survey.title, results_path(id: survey.id) %></td>
          <td>
            <%= pie_chart survey_answers_charts_path(id: survey.id), legend: false, width: '50px', height: '50px'  %>
          </td>
          <td class="survey-user"><%= survey.user.username %></td>
          <% if current_user && current_user.role.name == "Admin" %>
            <td><%= link_to '', survey_path(survey), :class => 'fa fa-times-circle',
              data: {:confirm => 'Are you sure?'}, :method => :delete %></td>
          <% else %>
            <td></td>
          <% end %>
        </tr>
        <% end %>
      </tbody>
    </table>
    <nav aria-label="Page navigation">
      <% if @surveys.any? %>
      <%= will_paginate @surveys, renderer: BootstrapPagination::Rails  %>
      <% else %>
      <p class="empty">No surveys yet.</p>
      <% end %>
    </nav>
  </div>
</div>

app/views/surveys/new.html.erb
<%= render 'form' %>

app/views/surveys/results.html.erb
<div class="row-fluid">
  <div class="col-md-8 col-md-offset-2">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title" style="font-size: 1.5em;"><%= @survey.title %> <br><small>Created by: <%= @survey.user.username %></small>
          <div class="pane-title pull-right"><%= link_to 'Submit Answer', survey_path(@survey), :class => "btn btn-success btn-sm" %></div>
          <div class="clearfix"></div>
        </h3>
      </div>
      <div class="panel-body">
        <h4> Total Votes: <%= @total %> </h4>
          <% answer_array = [] %>
        <% @survey.answers.each do |answer| %>
          <% answer_array.push(["#{answer.body}",answer.votes]) %>
        <% end %>
        <%= pie_chart(answer_array) %>
      </div>
      <div class="social-share">
        <a href="#" class="fb-share"><%= image_tag("FB-f-Logo__blue_50.png", :alt=> "facebook logo") %>Share on Facebook</a>
        <div id="fb-root"></div>
      </div>
    </div>
  </div>
<div id="comments-list" class="col-md-8 col-md-offset-2">
  <h1>Comments</h1>
  <% if @survey.comments.any? %>
    <%= render 'comments' %>
  <% else %>
  <% end %>
</div>
<div class="col-md-8 col-md-offset-2">
  <a href="#commentForm" type="button" class="btn btn-default" data-toggle="collapse">
    Add Comment
  </a>
</div>

<div id="commentForm" class="col-md-8 col-md-offset-2 collapse">
  <!-- form for comment -->
  <% if current_user %>
    <%= render 'comments_form' %>
  <% else %>
    <p>You must be logged in to leave a comment</p>
  <% end %>
  <!-- form for comment -->
</div>


</div>
<script type="text/javascript">
(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id))
        return;
    js = d.createElement(s);
    js.id = id;
    js.src = "//connect.facebook.net/en_US/all.js";
    fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));

window.fbAsyncInit = function() {
    FB.init({
        appId: <%= ENV['APP_ID'] %>,
        status: true,
        xfbml: true,
        cookie: true
    });
};

$(document).ready(function() {
    $('.fb-share').click(function() {
        FB.ui({
            method: 'feed',
            name: '<%= @survey.title %>',
            link: 'https://survey-constructor.herokuapp.com/tab_results?id=<%= @survey.id %>',
            picture: 'http://www.deweybanks.com/assets/SurveyMaker-ac6803449037a5916edf18838eee9e7895fb310c0157d11e481bf863604fdba5.png',
            description: 'SurveyMaker is an app for creating and taking surveys.'
        });
    });
});

</script>

app/views/surveys/show.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <div class="page-header">
      <h1><%= @survey.title %> <br><small>Created by: <%= @survey.user.username %></small></h1>
    </div>
    <h4>Choose your answer . . .</h4>
    <form action="/tab_results" method="post" accept-charset="utf-8">
      <input type="hidden" name="<%= request_forgery_protection_token.to_s %>" value="<%= form_authenticity_token %>">
      <input type="hidden" name="survey_id" value="<%= @survey.id %>">
      <select class="form-control" name="answer_id" id="answer_id">
        <% @survey.answers.each do |answer| %>
          <option value="<%= answer.id %>"><%= answer.body %></option>
        <% end %>
      </select>
      <br>
      <input class="btn btn-success" type="submit" name="submit">
    </form>
  </div>
</div>